apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ykra8022m-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:877b4a81e38ea51930b624ac1ec02f1c2a9666ed@sha256:33605f3e8289da01c4806822cf40266beab38bd6160fdf40871a0f0f1f6b84ca
          name: container-image
